#' Wait until
#'
#' @param until.time POSIXlt time stamp
#' @param pause.secs integer. seconds to pause between checking if \code{until.time} has been reached
#'
#' @return \code{NULL}
wait_until <- function(until.time, pause.secs = 5) {
  message("waiting until ", until.time)
  while (Sys.time() < until.time) {
    Sys.sleep(pause.secs)
  }
  NULL
}

#' Get running docker containers
#'
#' @description Functions uses \code{\link[base]{system}} to see what docker containers are running and
#'     returns running containers as a data frame.
#'     It throws an \code{Error} if docker is not installed or docker deamon is not running (incl informative message).
#'
#' @details The output is generated by runing \code{`docker ps --format '...'`} in the shell.
#'     Hence, a function call throws an \code{Error} if either
#'         (i) operating system is Windows,
#'         (ii) docker is not installed on system, or
#'         (iii) the docker deamon is not running.
#'
#' @section Warning:
#'     Currently implemented for Mac OSX/Unix/Linux only.
#'
#' @param format.string the formatting string passed to \code{`docker ps --format '<format string>'`}.
#'     Defaults to "table {{.Names}},{{.Image}},{{.ID}},{{.Ports}}"
#'
#' @return A data frame with columns as defined by \code{format.string},
#'      i.e. 'names', 'image', 'container_id', and 'ports' for the default formatting string.
#'      Each row representes one running container (hence, 0 rows if no container is running).
#'
#' @export
get_running_dockers <- function(format.string = "table {{.Names}},{{.Image}},{{.ID}},{{.Ports}}"){

  if (.Platform$OS.type != "unix") {
    stop("sorry, this method is currently not implemented for Windows operation system.", call. = FALSE)
  }

  if (identical(Sys.which("docker"), "")) {
    stop("Docker command line tool is not available on your system. (Consider installing it from https://www.docker.com/products/developer-tools)", call. = FALSE)
  }

  docker_stat <- tryCatch(
    system(sprintf("docker ps --format '%s' ", format.string), intern = TRUE)
    , warning = function(warn) warn
  )

  if (inherits(docker_stat, "warning"))
    stop("docker deamon not running. (Run `open --background -a Docker` in shell or start Docker.app to start deamon.)", call. = FALSE)

  stat <- do.call(rbind, strsplit(docker_stat, ","))
  setNames(as.data.frame(stat)[-1, ], gsub("\\s+", "_", tolower(stat[1, ])))
}
